Repository CESNET/perun-services, pull requests merged in 2018-11, with the labels that each got.

#380 Bug fix for processing $@ in catch_error function
  slave/base/bin/perun
  slave/base/changelog
Labels: bug, merge soon, waiting for review

#106 Safeq error handling and lines escaping/encoding
  gen/safeq
  send/safeq
Labels: merge soon

#383 Major change of content for o365 life cycle manager data export
  gen/o365_life_cycle_manager_mu
Labels: waiting for review
