Repository CESNET/perun-services, pull requests merged in 2020-09, with the labels that each got.

#477 ad_group_mu_ucn reworked updating members
  send/ad_group_mu_ucn
Labels: merge soon

#465 ad_mu process members in chunks
  send/ad_mu
Labels: merge soon

#478 Added grace period for groups in ad_mu
  send/ad_mu
Labels: merge soon

#479 Removed two unused variables assignment
  gen/fs_home
  gen/fs_home_mu
Labels: waiting for review

#481 Changes in service drupal_elixir
  gen/drupal_elixir
  slave/process-drupal-elixir/bin/process-drupal_elixir.sh
  slave/process-drupal-elixir/changelog
Labels: manual test needed, merge soon
