Repository CESNET/perun-services, pull requests merged in 2020-10, with the labels that each got.

#486 Suppress unnecessary TAR warnings about timestamps
  slave/base/bin/perun
  slave/base/changelog
Labels: merge soon

#414 Replace SUSPENDED state for new suspension logic for member
  gen/bbmri_collections
  gen/bbmri_networks
  gen/coffeeroom
  gen/drupal_elixir
  gen/fs_home
  gen/fs_home_mu
  gen/fs_scratch
  gen/kypo_portal
  gen/opennebula_egi
  gen/opennebula_meta
  gen/operations_portal_egi
  gen/pakiti
  gen/passwd
  gen/passwd_mu
  gen/scim
  gen/users_export
Labels: merge soon

#488 Fixed groupName and parentGroupId references in scim service
  gen/scim
Labels: merge soon

#487 Do not print to STDERR in generic_send if return code is zero
  send/appdb
  send/bbmri_collections
  send/bbmri_networks
  send/generic_send
  send/tinia
  send/topdesk
Labels: merge soon

#489 Fixed missing $ in variable name
  gen/bbmri_collections
  gen/bbmri_networks
  gen/coffeeroom
  gen/drupal_elixir
  gen/kypo_portal
  gen/pakiti
  gen/passwd
  gen/passwd_mu
  gen/scim
Labels: merge soon, waiting for review

#494 Removed unused services
  gen/coffeeroom
  gen/kypo_portal
  gen/opennebula_egi
  gen/opennebula_meta
  send/coffeeroom
  send/opennebula_egi
  send/opennebula_meta
  slave/process-coffeeroom/bin/process-coffeeroom.sh
  slave/process-coffeeroom/changelog
  slave/process-coffeeroom/dependencies
  slave/process-coffeeroom/rpm.dependencies
  slave/process-coffeeroom/short_desc
  slave/process-kypo-portal/bin/process-kypo_portal.sh
  slave/process-kypo-portal/changelog
  slave/process-kypo-portal/conf/example-db_settings.ini
  slave/process-kypo-portal/dependencies
  slave/process-kypo-portal/lib/process-kypo_portal.py
  slave/process-kypo-portal/rpm.dependencies
  slave/process-kypo-portal/short_desc
Labels: merge soon

#491 New service - Feudal
  gen/feudal
  send/feudal
Labels: merge soon

#495 Add support of getHashedDataMethod
  gen/perunServicesInit.pm
Labels: waiting for review

#493 Removed unused variable from the script for scim service
  gen/scim
Labels: merge soon
