Repository CESNET/perun-services, pull requests merged in 2021-09, with the labels that each got.

#623 fix(slave): prevent unnecessary update of modification timestamps on k5login files
  slave/process-k5login/bin/process-k5login.sh
  slave/process-k5login/changelog
Labels: merge soon

#638 fix(vsup_ifis): fixed variable name for deleted addresses counter
  send/vsup_ifis
Labels: merge soon, waiting for review

#636 feat(vsup): Modified ad_user_vsup* scripts
  gen/ad_user_vsup
  gen/ad_user_vsup_service
  send/ad_user_vsup
  send/ad_user_vsup_service
Labels: merge soon

#640 refactor: remove openvpn, users_export, samba_du, owncloud_vo_mapping
  gen/openvpn
  gen/owncloud_vo_mapping
  gen/samba_du
  gen/users_export
  send/openvpn
  send/owncloud_vo_mapping
  send/samba_du
  slave/meta/changelog
  slave/meta/rpm.dependencies
  slave/process-openvpn/bin/process-openvpn.sh
  slave/process-openvpn/changelog
  slave/process-openvpn/dependencies
  slave/process-openvpn/rpm.dependencies
  slave/process-openvpn/short_desc
Labels: waiting for review

#642 fix(tinia): resolve ban for all entries
  gen/tinia
Labels: waiting for review

#646 fix(ad_user_vsup_service): override displayName with adDisplayName value
  gen/ad_user_vsup_service
Labels: merge soon
