Repository CESNET/perun-services, pull requests merged in 2021-08, with the labels that each got.

#616 feat(gen): skipping inactive members in ad_group_mu_ucn
  gen/ad_group_mu_ucn
Labels: waiting for review

#615 refactor(send): removed locks from ad_mu service
  send/ad_mu
Labels: waiting for review

#617 perf(gen): use hashed data - bbmri*
  gen/bbmri_collections
  gen/bbmri_networks
Labels: waiting for review

#618 feat: kerberos_renewal_principals service
  gen/kerberos_renewal_principals
  send/kerberos_renewal_principals
  slave/meta/changelog
  slave/meta/rpm.dependencies
  slave/process-kerberos-renewal-principals/bin/process-kerberos_renewal_principals.sh
  slave/process-kerberos-renewal-principals/changelog
  slave/process-kerberos-renewal-principals/dependencies
  slave/process-kerberos-renewal-principals/rpm.dependencies
  slave/process-kerberos-renewal-principals/short_desc
Labels: merge soon

#631 refactor(gen): removed unused internal method params in drupal_elixir
  gen/drupal_elixir
Labels: merge soon, waiting for review

#630 refactor: removed unused service sympa-cesnet
  gen/sympa_cesnet
  send/sympa_cesnet
  slave/process-sympa-cesnet/bin/process-sympa_cesnet.sh
  slave/process-sympa-cesnet/changelog
  slave/process-sympa-cesnet/dependencies
  slave/process-sympa-cesnet/rpm.dependencies
  slave/process-sympa-cesnet/short_desc
Labels: waiting for review

#626 feat: added new service myq_printsvc
  gen/myq_printsvc
  send/myq_printsvc
Labels: merge soon, waiting for review

#629 feat(slave): fixed RHEL compatibility of perun_propagate
  other/perun-propagate/debian/changelog
  other/perun-propagate/debian/control
  other/perun-propagate/etc/perun_propagate
Labels: merge soon
