Repository CESNET/perun-services, pull requests merged in 2021-04, with the labels that each got.

#556 ad_user_mu_ucn service refactored and added new features
  gen/ad_user_mu_ucn
Labels: merge soon

#586 Added generic_send in Python
  send/generic_send.py
Labels: don't merge

#590 Services arcgis_mu, hadoop*, hml_json edited to use hashed data
  gen/arcgis_mu
  gen/hadoop_hbase
  gen/hadoop_hdfs
  gen/hml_json
Labels: waiting for review

#595 New service netbox
  gen/netbox
  send/netbox
Labels: waiting for review

#597 Updated slave scripts for fs_home and k5login
  slave/process-fs-home/bin/process-fs_home.sh
  slave/process-fs-home/changelog
  slave/process-k5login/bin/process-k5login.sh
  slave/process-k5login/changelog
Labels: waiting for review
