Repository CESNET/perun-services, pull requests merged in 2022-11, with the labels that each got.

#695 feat(scs_it4i): added scripts for scs_it4i service
  gen/scs_it4i
  send/scs_it4i
Labels: merge soon, waiting for review

#736 feat(banned_facility_users): new service for returning facility bans
  gen/banned_facility_users
  send/banned_facility_users
Labels: waiting for review, don't merge

#737 fix(ad_group_vsup): fail gracefully if no group name is set
  gen/ad_group_vsup
Labels: merge soon

#740 feat(myq_printsvc): change chip number format
  gen/myq_printsvc
Labels: waiting for review, manually tested

#741 feat(vsup_ifis): support IS backend in shared lib
  send/VsupIfis.pm
Labels: merge soon
