Repository CESNET/perun-services, pull requests merged in 2022-08, with the labels that each got.

#706 fix: fixed propagation using generic_send python script
  send/generic_send.py
Labels: merge soon, waiting for review

#710 feat: use generic_send.py in rt_data_vocesnet and users_emails
  send/rt_data_vocesnet
  send/users_emails
Labels: merge soon

#714 fix: make sure to always print STDERR in generic_send.py
  send/generic_send.py
Labels: merge soon, waiting for review

#716 fix: added missing space before ssh command port parameter
  send/generic_send.py
Labels: merge soon

#722 fix(afs_group): do not include expired members in afs groups
  gen/afs_group
Labels: merge soon

#720 refactor(o365_mu): Processing bulk of entities
  send/o365-connector.pl
  send/o365_mu_process.pl
Labels: merge soon, don't merge, manually tested, squash before merge

#726 fix(o365_mu): use correct cache file name
  send/o365_mu_process.pl
Labels: waiting for review
