Repository CESNET/perun-services, pull requests merged in 2022-05, with the labels that each got.

#681 fix(openstack_projects): correctly use EPPN attribute to include all identifiers
  gen/openstack_projects
Labels: merge soon

#685 feat(ad_group_mu_ucn): convert only invalid values to base64
  gen/ad_group_mu_ucn
Labels: merge soon

#676 feat: added local changes and unversioned scripts from idm instance
  gen/elerning_mu_ff
  gen/teams_provisioning
  send/ad_user_mu_ucn
  send/crm_ceitec
  send/elerning_mu_ff
  send/netbox
  send/teams_provisioning
Labels: merge soon

#684 feat(gen): Manually run consent in gen scripts
  gen/perunServicesInit.pm
Labels: manual test needed, don't merge

#689 feat: removed redundant filterExpiredMembers parameter
  gen/ad_admin_group_mu_ucn
  gen/ad_admin_user_mu_ucn
  gen/ad_group_mu_ucn
  gen/ad_user_mu_ucn
  gen/arcgis_licenses_mu
  gen/insight_mu
  gen/netbox
  gen/perunServicesInit.pm
Labels: waiting for review

#692 fix(netbox): fixed path to shared configuration
  send/netbox
Labels: merge soon

#691 feat(insight_mu): sort json output to be comparable
  gen/insight_mu
Labels: merge soon

#690 feat(arcgis_licenses_mu): sort json output to be comparable
  gen/arcgis_licenses_mu
Labels: merge soon
