Repository CESNET/perun-services, pull requests merged in 2022-04, with the labels that each got.

#670 feat(rt_data_vocesnet): added service pushing vo cesnet data to RT
  gen/rt_data_vocesnet
  send/rt_data_vocesnet
  slave/process-rt-data-vocesnet/bin/process-rt_data_vocesnet.sh
  slave/process-rt-data-vocesnet/changelog
  slave/process-rt-data-vocesnet/dependencies
  slave/process-rt-data-vocesnet/rpm.dependencies
  slave/process-rt-data-vocesnet/short_desc
Labels: waiting for review

#677 fix(crm_ceitec): support working in the container
  send/crm_ceitec
Labels: merge soon

#682 fix(fs_home): set data limit to 0 if missing
  gen/fs_home
Labels: merge soon

#678 feat(insight_mu): new service for Jira insight
  gen/insight_mu
  send/insight-connector.pl
  send/insight_mu
Labels: don't merge
