Repository CESNET/perun-services, pull requests merged in 2023-10, with the labels that each got.

#832 feat(hml_json): changed hml_json gen script to use scoped mu login
  gen/hml_json
Labels: waiting for review

#833 fix(vsup_ifis): use only relations from stag
  send/vsup_ifis
Labels: merge soon

#841 refactor(atlassian_mu): removed temporary method for _del prefix
  send/atlassian_mu_process.pl
Labels: waiting for review

#839 fix: 🐛 Use LS ID in BBMRI scripts
  gen/bbmri_collections
  gen/bbmri_networks
Labels: merge soon, manually tested

#840 docs: dhus documentation
  docs/README.md
  docs/concepts/gen.md
  docs/concepts/pre-mid-post.md
  docs/concepts/script-structure.md
  docs/concepts/send.md
  docs/concepts/slave.md
  docs/modules/PerunDataGenerator.md
  docs/modules/generic_sender.md
  docs/services/dhus.md
  docs/services/webcentrum_eosc.md
Labels: waiting for review

#836 feat(m365_cloud): new service for provisioning to m365
  docs/m365_cloud.md
  gen/m365_cloud
  gen/perunDataGenerator.pm
  send/m365_cloud
  send/send_lib.py
Labels: don't merge
