Repository CESNET/perun-services, pull requests merged in 2023-09, with the labels that each got.

#816 feat(pithia_portal): added authorization token support
  send/pithia_portal
Labels: waiting for review

#826 fix(scs_it4i): use send_lib.py, support v2 API
  gen/scs_it4i
  send/scs_it4i
Labels: merge soon, manually tested

#817 feat(atlassian_mu): add 'del_' prefix to inactive users
  send/atlassian_mu_process.pl
Labels: waiting for review, manually tested

#827 feat(o365_mu_ukb_forward_status): add new service
  gen/o365_mu_ukb_forward_status
  send/o365_mu_ukb_forward_status
  slave/process-o365-mu-ukb-forward-status/bin/process-o365_mu_ukb_forward_status.sh
  slave/process-o365-mu-ukb-forward-status/changelog
  slave/process-o365-mu-ukb-forward-status/conf/example-pre_01_set_target_dir
  slave/process-o365-mu-ukb-forward-status/dependencies
  slave/process-o365-mu-ukb-forward-status/rpm.dependencies
  slave/process-o365-mu-ukb-forward-status/short_desc
Labels: waiting for review
