Repository CESNET/perun-services, pull requests merged in 2023-05, with the labels that each got.

#781 refactor(k5login_root): removed usage of listOfDestinations attribute
  gen/k5login_root
Labels: merge soon

#768 feat(tinia): use python send script
  send/send_lib.py
  send/tinia
Labels: manual test needed

#785 fix(atlassian_mu): return verbose response from process script
  send/atlassian_mu
  send/send_lib.py
Labels: manually tested

#786 fix(o365_mu_users_export): copy also MFA file
  send/o365_mu_users_export
Labels: merge soon, waiting for review

#783 feat(feudal): rewrite feudal send script to python
  send/feudal.py
Labels: waiting for review, manual test needed, don't merge
