Repository CESNET/perun-services, pull requests merged in 2023-06, with the labels that each got.

#788 feat(crocs_user_export): rewrite send script to python
  send/crocs_user_export
Labels: waiting for review, manual test needed

#790 feat: extend the generic gen functionality
  gen/perunDataGenerator.pm
Labels: waiting for review

#792 feat(ftps_generic): new service for explicit ftps file transport
  gen/ftps_generic
  send/ftps_generic
  send/send_lib.py
Labels: waiting for review

#795 feat(umbraco_mu): change send script to use BA credentials
  send/send_lib.py
  send/umbraco_mu
Labels: waiting for review, manually tested
